[03-Aug-2020 17:02:45 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 18:59:25 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 104' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 13:59:25 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading authorization packet', system error: 0' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:01:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 19:01:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 19:02:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 19:02:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:02:57 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:02:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:02:57 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:08 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 19:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:17 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:30 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:33 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:33 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:33 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:36 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:38 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:43 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:43 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:43 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 14:03:45 America/Lima] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/agregar_registro.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:03:48 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:04:11 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:08:40 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:08:51 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:03 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:41 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:45 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:49 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:51 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:56 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:09:58 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:19:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 19:21:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:21:45 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:22:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:22:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:22:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:22:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:03 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:41 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:55 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:23:56 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:24:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:24:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:24:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:25:07 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:25:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:25:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:28:08 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:28:09 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:28:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:32:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:39 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:39 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:51:44 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:52:24 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:52:25 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:52:50 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:52:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:53:12 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:53:12 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:58:11 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:59:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 19:59:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:01:53 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (11)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 104' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 104' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 95' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 95' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'reading initial communication packet', system error: 95' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2013] Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query' in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(8): PDOStatement->execute()
#1 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/estado.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:18 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:18 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:19 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:28 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:30 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:31 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:32 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:32 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:32 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:33 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:34 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:03:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:10:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:11:13 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:11:23 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:12:08 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:13:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:13:27 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:14:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:14:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:14:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:14:44 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:14:54 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/actualizar_datos.php(4): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:15:40 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:15:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:15:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:15:51 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:16:03 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:16:10 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:16:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:16:55 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:19:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:28 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:28 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:20:49 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:21:13 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:21:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:21:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:21:22 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:22:32 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 20:23:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:01:04 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:01:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:12 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:25 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:02:28 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:03:04 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:04:56 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:02 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:11 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:14 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:55 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:55 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:55 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:57 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:05:59 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:00 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:01 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:15 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:17 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:20 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:25 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:25 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:29 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:49 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:06:59 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:07:07 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:07:11 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:07:13 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:07:20 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:08:52 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:21 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:27 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:28 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:29 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:29 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:29 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:30 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:30 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:36 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:40 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:42 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:11:43 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:23:44 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:23:51 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:23:54 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:24:07 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[03-Aug-2020 23:35:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:12 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:35 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:38 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:41 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:41 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:41 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:45 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:46 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:46 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
[04-Aug-2020 14:55:51 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)' in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php:8
Stack trace:
#0 /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php(8): PDO->__construct('mysql:host=loca...', 'asistencia_user', 'S1st3m4s2018', Array)
#1 /home/o6kzt2ztwtl7/public_html/asistencia/estado.php(3): connect()
#2 {main}
  thrown in /home/o6kzt2ztwtl7/public_html/asistencia/conexion.php on line 8
